import { FontTesterBase } from './base.js';
import { FontDisplay } from './components/FontDisplay.js';
import { SampleTextSelector } from './components/SampleTextSelector.js';
import { TextControls } from './components/TextControls.js';
import { StyleControls } from './components/StyleControls.js';
import { FontStyleSelector } from './components/FontStyleSelector.js';
import { OpentypeFeatures } from './components/OpentypeFeatures.js';
import { SampleText, OpentypeFeature, FontStyle } from './markers/index.js';
import { FontTester } from './FontTester.js';

export { FontTesterBase };
export const initTranslations = () => FontTesterBase.initTranslations();
export { FontDisplay };
export { SampleTextSelector };
export { TextControls };
export { StyleControls };
export { FontStyleSelector };
export { OpentypeFeatures };
export { SampleText, OpentypeFeature, FontStyle };
export { FontTester };

customElements.define( 'font-display', FontDisplay );
customElements.define( 'sample-text-selector', SampleTextSelector );
customElements.define( 'text-controls', TextControls );
customElements.define( 'style-controls', StyleControls );
customElements.define( 'font-style-selector', FontStyleSelector );
customElements.define( 'opentype-features', OpentypeFeatures );
customElements.define( 'font-tester', FontTester );
customElements.define( 'sample-text', SampleText );
customElements.define( 'opentype-feature', OpentypeFeature );
customElements.define( 'font-style', FontStyle );
